name: Release Demo Page

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: login
      run: |
        git config --global user.email ${{ secrets.email }}
        git config --global user.name "any86"
    - name: release demo page
      run: |
        npm install
        npm run release:demo
